/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/presentation/components/layout/LandingPage.tsx",
    "./src/presentation/components/layout/landing/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#5f656c",
        "tertiary-fixed": "#d4e4fa",
        "on-background": "#191c1e",
        "on-primary": "#ffffff",
        "secondary": "#595f66",
        "surface-canvas": "#F4F5F8",
        "on-primary-fixed-variant": "#00522d",
        "border-strong": "#CBD5E1",
        "surface-bright": "#f8f9fc",
        "inverse-surface": "#2e3133",
        "primary-fixed-dim": "#73db9a",
        "on-tertiary-fixed-variant": "#39485a",
        "surface-dim": "#d9dadd",
        "text-secondary": "#4B5563",
        "secondary-fixed-dim": "#c1c7cf",
        "outline-variant": "#bdcabe",
        "secondary-container": "#dde3eb",
        "on-surface-variant": "#3e4a40",
        "on-primary-container": "#006d3e",
        "surface-container-highest": "#e1e2e5",
        "primary-fixed": "#8ff8b4",
        "on-surface": "#191c1e",
        "accent-mint-deep": "#16A34A",
        "text-muted": "#94A3B8",
        "inverse-primary": "#73db9a",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#41474e",
        "surface-variant": "#e1e2e5",
        "on-primary-fixed": "#00210f",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e7e8eb",
        "surface-card": "#FFFFFF",
        "primary-container": "#86efac",
        "on-tertiary": "#ffffff",
        "outline": "#6e7a70",
        "surface-tint": "#006d3e",
        "surface-container": "#edeef1",
        "tertiary-container": "#ccdbf1",
        "on-tertiary-container": "#516073",
        "border-subtle": "#E2E8F0",
        "on-tertiary-fixed": "#0d1c2d",
        "surface-container-low": "#f2f3f6",
        "on-error": "#ffffff",
        "tertiary": "#516072",
        "surface": "#f8f9fc",
        "on-secondary-fixed": "#161c22",
        "background": "#f8f9fc",
        "primary": "#006d3e",
        "inverse-on-surface": "#f0f1f4",
        "secondary-fixed": "#dde3eb",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#b9c8de",
        "text-primary": "#111827",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "space-xs": "0.25rem",
        margin: "3rem",
        "space-sm": "0.5rem",
        gutter: "1.5rem",
        "space-md": "1rem",
        "space-xl": "2.5rem",
        "margin-mobile": "1.25rem",
        "gutter-mobile": "1rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "headline-sm": ["Geist"],
        "headline-md": ["Geist"],
        "display-mobile": ["Geist"],
        "label-meta": ["Inter"],
        "headline-lg": ["Geist"],
        "headline-lg-mobile": ["Geist"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "label-code": ["JetBrains Mono"],
        display: ["Geist"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "display-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "label-meta": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "label-code": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        display: ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "600" }]
      }
    }
  },
  plugins: [],
}
